version: '3.8'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api-server
    ports:
      - "8081:8081"
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: unless-stopped

  neurodlb-bot:
    build: .
    container_name: neurodlb-bot
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_API_URL=http://telegram-bot-api:8081
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - telegram-bot-api
    # Remove this for production
    stdin_open: true
    tty: true
